### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by margiofabiolad** [dgrin1/axionCAMB#12]
Hi, 
I was modifying the files that you mention in bugfix_compare, to work only with the code after debugging to obtain output files. Maybe I edit some of the files incorrectly and now it show me this error: 

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

```
Backtrace for this error:
#0  0x7fb107623ad0 in ???
#1  0x7fb107622c35 in ???
#2  0x7fb10724251f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x560c0dca46d4 in ???
#4  0x560c0dcca66e in ???
#5  0x560c0dcae0d3 in ???
#6  0x560c0dcf076f in ???
#7  0x560c0dcf4c0d in ???
#8  0x560c0dcf62f4 in ???
#9  0x560c0dd01ce3 in ???
#10  0x560c0dd023c4 in ???
#11  0x7fb107229d8f in __libc_start_call_main
	at ../sysdeps/nptl/libc_start_call_main.h:58
#12  0x7fb107229e3f in __libc_start_main_impl
	at ../csu/libc-start.c:392
#13  0x560c0dc774c4 in ???
#14  0xffffffffffffffff in ???
Segmentation fault (core dumped)
mv: no se puede efectuar `stat' sobre 'test_scalCls.dat': No existe el archivo o el directorio
```

How o what I shoulb modify to generate the test_scalar.dat again?

**Comment by dgrin1** [comment]
I have found this issue can arise with some compiler flags (ones that speed up the computer on some machines), or various fortran compilers (g95 vs gfortran).**SUCH issues have been more or less resolved with the newer code axieCAMB, which is much more accurate, as well -- I strongly encourage you to switch ASAP to axieCAMB - the structure and interface is built on axionCAMB, and should be easier to use but much more robust.** I hope this is helpful.
